version: '3'
services:
  server:
    build:
      context: ./api
    restart: always
    ports:
      - '5000:5000'

  web:
    build:
      context: ./dashboard
    restart: always
    ports:
      - '3000:80'
